# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Chris Davis
tagline:          'Welcome'
description:      'Welcome to my site!'
url:              https://chrispdavis.github.io/
baseurl:          https://chrispdavis.github.io/

author:
  name:           'Chris Davis'
  url:            https://chrispdavis.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chrispdavis/chrispdavis.github.io/
